system:
  log_level: "DEBUG"         
  log_file: "logs/system.log"

receive_img:
  rtsp_url: "rtsp://10.61.35.243:8554/stream"
  http_url: "http://10.61.35.243:1984/image"
  buffer_size: 1             

object_detection:
  yolo_model: "models/obj_model/best.engine"
  confidence_threshold: 0.5
  img_size: 640
