system:
  log_level: "DEBUG"         
  log_file: "logs/system.log"

receive_img:
  rtsp_url: "rtsp://10.61.35.243:8554/stream"
  buffer_size: 1             

object_detection:
  yolo_model: "yolo11n.pt"
  confidence_threshold: 0.5
  img_size: 640

