system:
  log_level: "DEBUG"         
  log_file: "logs/system.log"

receive_img:
  rtsp_url: "rtsp://10.61.35.243:8554/stream"
  http_url: "http://10.61.35.243:1984/image"
  buffer_size: 1         


output_stream:
  ip_address: "0.0.0.0"
  port: 9806
  mounts:
    od: "/od"
    ocr: "/ocr"
    analog: "/analog"
    classification: "/cls"
  width: 640
  height: 480
  fps: 30



object_detection:
  yolo_model: "models/obj_model/best.engine"
  confidence_threshold: 0.5
  img_size: 640


ocr:
  model_dir: "MissionAI/models/digital_gauge_model/best_model.pt"
  device: "cuda"
  confidence_threshold: 0.8
